### ISSUE TITLE
The parse job crashes if one of the values of the ppe_product_types array field exceeds the max length of 50 characters

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1061]
## Overview

The parse job crashes if one of the values of a `ppe_product_types` array field exceeds the max length of 50 characters.

### Expected Behavior

When processing a list if one of the values of a `ppe_product_types` array field exceeds the max length of 50 characters the processing job completes successfully and the line is moved to the`ERROR_PARSING` status and shows an informative validation error message.

### Actual Behavior

When processing a list if one of the values of a `ppe_product_types` array field exceeds the max length of 50 characters the batch_process job crashes with an unhanded exception and the line is stuck in the `UPLOADED` status.

### Steps to Reproduce

These steps assume `./scripts/resetdb` has been run.

* Log in as c2@example.com
* Upload [single-item-ppe-product-type-too-long.csv.zip](https://github.com/open-apparel-registry/open-apparel-registry/files/4997568/single-item-ppe-product-type-too-long.csv.zip)
* Run the parse job
  * ./scripts/manage batch_process --list-id 16 --action parse

### Demo

```
vagrant@vagrant:/vagrant$ ./scripts/manage batch_process --list-id 16 --action parse
Starting vagrant_database_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InvalidTextRepresentation: malformed array literal: ""
LINE 1: ... "api_facilitylistitem" SET "ppe_product_types" = ''::varcha...
                                                             ^
DETAIL:  Array value must start with "{" or dimension information.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/src/api/management/commands/batch_process.py", line 65, in handle
    self.process_items(facility_list, action, process)
  File "/usr/local/src/api/management/commands/batch_process.py", line 124, in process_items
    item.save()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1469, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: malformed array literal: ""
LINE 1: ... "api_facilitylistitem" SET "ppe_product_types" = ''::varcha...
                                                             ^
DETAIL:  Array value must start with "{" or dimension information.
```

**Comment by jwalgran** [comment]
Shares point with https://github.com/open-apparel-registry/open-apparel-registry/issues/1061
