### ISSUE TITLE
GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSWKBReader_read_r".

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1070]
An exception was raised when attempting to request facilities from the API with an invalid geometry.

```
{
  "boundary": "{\"type\":\"GeometryCollection\",\"geometries\":[{\"type\":\"MultiPolygon\",\"coordinates\":[[[[20.64468,52.38021],[21.47827,52.08584]]]]}]}",
  "page": "1",
  "pageSize": "5"
}
```

View details in Rollbar: [https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/501/](https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/501/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/src/api/views.py", line 720, in list
    .filter_by_query_params(request.query_params) \
  File "/usr/local/src/api/models.py", line 1199, in filter_by_query_params
    location__within=GEOSGeometry(boundary)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/gis/geos/geometry.py", line 712, in __init__
    g = ogr._geos_ptr()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/gis/gdal/geometries.py", line 312, in _geos_ptr
    return GEOSGeometry._from_wkb(self.wkb)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/gis/geos/geometry.py", line 113, in _from_wkb
    return wkb_r().read(wkb)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/gis/geos/prototypes/io.py", line 151, in read
    return wkb_reader_read(self.ptr, wkb_s, len(wkb_s))
  File "/usr/local/lib/python3.7/site-packages/django/contrib/gis/geos/libgeos.py", line 155, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/gis/geos/prototypes/threadsafe.py", line 47, in __call__
    return self.cfunc(self.thread_context.handle.ptr, *args)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/gis/geos/prototypes/errcheck.py", line 32, in check_geom
    'raise GEOSException(\'Error encountered checkin...ed from GEOS C function "%s".\' % func.__name__)'
GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSWKBReader_read_r".
```

**Comment by jwalgran** [comment]
Merging into #2179
