### ISSUE TITLE
Error loading the site on production

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1747]
![image.png](https://images.zenhubusercontent.com/61ae9d06cd0ba9a0bcfc8c87/30810da7-b83c-453c-831e-6470582ac099)

Code copied:
ZS5tYXAgaXMgbm90IGEgZnVuY3Rpb24gOjo6Ojo6OiBUeXBlRXJyb3I6IGUubWFwIGlzIG5vdCBhIGZ1bmN0aW9uCiAgICBhdCB1aCAoaHR0cHM6Ly9vcGVuYXBwYXJlbC5vcmcvc3RhdGljL2pzL21haW4uZTAxMTIyOGYuY2h1bmsuanM6MToxOTMzOTEpCiAgICBhdCBiaCAoaHR0cHM6Ly9vcGVuYXBwYXJlbC5vcmcvc3RhdGljL2pzL21haW4uZTAxMTIyOGYuY2h1bmsuanM6MToyMDE5ODEpCiAgICBhdCBKbyAoaHR0cHM6Ly9vcGVuYXBwYXJlbC5vcmcvc3RhdGljL2pzLzIuYjkwYjg4OTIuY2h1bmsuanM6MjoyNzY0MzA0KQogICAgYXQgeHMgKGh0dHBzOi8vb3BlbmFwcGFyZWwub3JnL3N0YXRpYy9qcy8yLmI5MGI4ODkyLmNodW5rLmpzOjI6MjgxMDUzNCkKICAgIGF0IHZsIChodHRwczovL29wZW5hcHBhcmVsLm9yZy9zdGF0aWMvanMvMi5iOTBiODg5Mi5jaHVuay5qczoyOjI4MDMyNjEpCiAgICBhdCBnbCAoaHR0cHM6Ly9vcGVuYXBwYXJlbC5vcmcvc3RhdGljL2pzLzIuYjkwYjg4OTIuY2h1bmsuanM6MjoyODAzMTg2KQogICAgYXQgc2wgKGh0dHBzOi8vb3BlbmFwcGFyZWwub3JnL3N0YXRpYy9qcy8yLmI5MGI4ODkyLmNodW5rLmpzOjI6MjgwMDE5NSkKICAgIGF0IGh0dHBzOi8vb3BlbmFwcGFyZWwub3JnL3N0YXRpYy9qcy8yLmI5MGI4ODkyLmNodW5rLmpzOjI6Mjc1MTU2NgogICAgYXQgZS51bnN0YWJsZV9ydW5XaXRoUHJpb3JpdHkgKGh0dHBzOi8vb3BlbmFwcGFyZWwub3JnL3N0YXRpYy9qcy8yLmI5MGI4ODkyLmNodW5rLmpzOjI6MjgyNjk2NykKICAgIGF0IFlpIChodHRwczovL29wZW5hcHBhcmVsLm9yZy9zdGF0aWMvanMvMi5iOTBiODg5Mi5jaHVuay5qczoyOjI3NTEyNzUp

**Comment by TaiWilkin** [comment]
"Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops." https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/1137/

**Comment by TaiWilkin** [comment]
'e.map is not a function ::::::: TypeError: e.map is not a function\n    at uh (https://openapparel.org/static/js/main.e011228f.chunk.js:1:193391)\n    at bh (https://openapparel.org/static/js/main.e011228f.chunk.js:1:201981)\n    at Jo (https://openapparel.org/static/js/2.b90b8892.chunk.js:2:2764304)\n    at xs (https://openapparel.org/static/js/2.b90b8892.chunk.js:2:2810534)\n    at vl (https://openapparel.org/static/js/2.b90b8892.chunk.js:2:2803261)\n    at gl (https://openapparel.org/static/js/2.b90b8892.chunk.js:2:2803186)\n    at sl (https://openapparel.org/static/js/2.b90b8892.chunk.js:2:2800195)\n    at https://openapparel.org/static/js/2.b90b8892.chunk.js:2:2751566\n    at e.unstable_runWithPriority (https://openapparel.org/static/js/2.b90b8892.chunk.js:2:2826967)\n    at Yi (https://openapparel.org/static/js/2.b90b8892.chunk.js:2:2751275)'
