### ISSUE TITLE
Exception when loading the Django admin

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#188]
## Overview

Cannot load the Django admin

### Expected Behavior

Browsing `/admin/` shows a list of models.

### Actual Behavior

An unhandled exception prevents that page from loading

### Steps to Reproduce

* Browse `/admin/` login

### Additional context

```
django_1    | [2019-02-07 18:59:37 +0000] [8] [DEBUG] GET /admin/
django_1    | Internal Server Error: /admin/
django_1    | Traceback (most recent call last):
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
django_1    |     response = get_response(request)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
django_1    |     response = self.process_exception_by_middleware(e, request)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
django_1    |     response = response.render()
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 106, in render
django_1    |     self.content = self.rendered_content
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
django_1    |     content = template.render(context, self._request)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
django_1    |     return self.template.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 175, in render
django_1    |     return self._render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 167, in _render
django_1    |     return self.nodelist.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 943, in render
django_1    |     bit = node.render_annotated(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
django_1    |     return self.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 155, in render
django_1    |     return compiled_parent._render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 167, in _render
django_1    |     return self.nodelist.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 943, in render
django_1    |     bit = node.render_annotated(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
django_1    |     return self.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 155, in render
django_1    |     return compiled_parent._render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 167, in _render
django_1    |     return self.nodelist.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 943, in render
django_1    |     bit = node.render_annotated(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
django_1    |     return self.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 314, in render
django_1    |     return nodelist.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 943, in render
django_1    |     bit = node.render_annotated(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
django_1    |     return self.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 67, in render
django_1    |     result = block.nodelist.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 943, in render
django_1    |     bit = node.render_annotated(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
django_1    |     return self.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 314, in render
django_1    |     return nodelist.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 943, in render
django_1    |     bit = node.render_annotated(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
django_1    |     return self.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 67, in render
django_1    |     result = block.nodelist.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 943, in render
django_1    |     bit = node.render_annotated(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
django_1    |     return self.render(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 122, in render
django_1    |     value = var.resolve(context, True)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 676, in resolve
django_1    |     obj = self.var.resolve(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 802, in resolve
django_1    |     value = self._resolve_lookup(context)
django_1    |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 864, in _resolve_lookup
django_1    |     current = current()
django_1    |   File "/usr/local/src/api/models.py", line 148, in get_short_name
django_1    |     return self.name
```

**Comment by rbreslow** [comment]
See: https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/3/
