### ISSUE TITLE
Processing demo list 14 causes the geocoding process to crash

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#292]
## Overview

Processing demo list 14 causes the geocoding process to crash. There may be bad data in the list but whatever's in it breaks the exception handling.

### Expected Behavior

geocoding list 14 succeeds

### Actual Behavior

geocoding list 14 fails with the following message:

```
Exception ignored in: <function CPointerBase.__del__ at 0x7fbe04b19620>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/contrib/gis/ptr.py", line 36, in __del__
  File "/usr/local/lib/python3.7/site-packages/django/contrib/gis/geos/libgeos.py", line 155, in __call__
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 36, in __get__
  File "/usr/local/lib/python3.7/site-packages/django/contrib/gis/geos/libgeos.py", line 159, in func
ImportError: sys.meta_path is None, Python is likely shutting down
```

### Steps to Reproduce

- upload demo list 14
- parse demo list 14
- geocode demo list 14

**Comment by jwalgran** [comment]
We ran into a problem before with that exception masking an actual problem with inconsistent fixture data:

https://github.com/open-apparel-registry/open-apparel-registry/pull/195#issuecomment-462849518

**Comment by jwalgran** [comment]
Likely the same as 292
