### ISSUE TITLE
ecsmanage command failing to look up staging security group

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#295]
## Overview

`ecsmanage` is failing to launch tasks.

### Expected Behavior

`./scripts/manage ecsmanage version` successfully launches a task.

### Actual Behavior

An exception is raised

```
vagrant@vagrant:/vagrant$ ./scripts/manage ecsmanage version
Starting vagrant_database_1 ... done
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/src/api/management/commands/ecsmanage.py", line 36, in handle
    security_group_id = self.get_security_group()
  File "/usr/local/src/api/management/commands/ecsmanage.py", line 109, in get_security_group
    security_group = self.parse_response(sg_response, 'SecurityGroups', 0)
  File "/usr/local/src/api/management/commands/ecsmanage.py", line 60, in parse_response
    raise KeyError(msg)
KeyError: "Unexpected response from ECS API: {'SecurityGroups': [], 'ResponseMetadata': {'RequestId': '2e5ac9e9-c1af-4283-9b90-756429396533', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'text/xml;charset=UTF-8', 'transfer-encoding': 'chunked', 'vary': 'Accept-Encoding', 'date': 'Tue, 12 Mar 2019 20:38:01 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}"
vagrant@vagrant:/vagrant$ AWS_PROFILE=open-apparel-registry aws ec2 describe-security-groups
SECURITYGROUPS	default VPC security group	sg-f36713b0	default	249322298638	vpc-9f48fde5
IPPERMISSIONS	-1
USERIDGROUPPAIRS	sg-f36713b0	249322298638
IPPERMISSIONSEGRESS	-1
IPRANGES	0.0.0.0/0
```

### Steps to Reproduce

* On the VM run `./scripts/manage ecsmanage version`

**Comment by rbreslow** [comment]
As a troubleshooting measure, I would double check that you have rebased against the latest changes on the `develop` branch.

I cannot replicate on `develop` within the VM:

```bash
vagrant@vagrant:/vagrant$ ./scripts/manage ecsmanage version
Starting vagrant_database_1 ... done
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
Task started! View here:

https://console.aws.amazon.com/ecs/home?region=eu-west-1#/clusters/ecsStagingCluster/tasks/2df94c15-dea2-49c2-ad61-a877015dcee0/details
vagrant@vagrant:/vagrant$ 
```

The error you're getting makes me think it's looking for security groups in `us-east-1`, but there aren't any, since we've moved everything to `eu-west-1`.

**Comment by jwalgran** [comment]
Thanks for looking into this. Yep, my bad. I forgot to update ~/.aws/config on my host machine to use eu-west-1. After fixing that I had no trouble using `ecsmanage`
