### ISSUE TITLE
EmptyResultSet

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#845]
View details in Rollbar: [https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/288/](https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/288/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/waffle/decorators.py", line 50, in _wrapped_view
    return view(request, *args, **kwargs)
  File "/usr/local/src/api/views.py", line 2361, in get_tile
    request.query_params, layer, z, x, y)
  File "/usr/local/src/api/tiler.py", line 35, in get_facility_grid_vector_tile
    .values('location') \
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 273, in sql_with_params
    return self.get_compiler(DEFAULT_DB_ALIAS).as_sql()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 489, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 405, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/where.py", line 99, in as_sql
    raise EmptyResultSet
EmptyResultSet
```

**Comment by kellyi** [comment]
This happens when the filters for the requested set of facilities results in an empty queryset.

Two approaches to solve it:

- if the Leaflet map's vector grid components won't break because of this, return a 204 for requests which result in empty facilities querysets being used to try to create a tile -- prior to trying to create the tile
- if the Leaflet map's vector grid components do break on a 204, return an empty tile instead. In this case it'd probably be worthwhile to write a function that will generate an empty tile for whatever x/y/z params combo.

**Comment by jwalgran** [comment]
We should try the simpler, empty 204 response first.

**Comment by jwalgran** [comment]
https://docs.djangoproject.com/en/2.2/ref/exceptions/#emptyresultset
>EmptyResultSet may be raised during query generation if a query won’t return any results. Most Django projects won’t encounter this exception, but it might be useful for implementing custom lookups and expressions

**Comment by jwalgran** [comment]
I was able to trigger this by loading this search and quickly zooming in, but I could not refresh the page and repeat the errors.

https://openapparel.org/?contributors=78&contributor_types=Auditor
